name: jueymobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#0E0E0E"
  adaptive_icon_foreground: assets/icons/app_icon_foreground.png
